version: 2
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      - git fetch --unshallow || true

sphinx:
  configuration: docs/source/conf.py

formats: all

python:
  install:
    - requirements: docs/requirements.txt